---
info:
  version: '1.0'
definitions:
  DatasetCreatePayload:
    type: object
    description: |
      The payload used to create a dataset.

      TODO: require a layer id
    properties:
      id:
        type: string
    required:
    - id
channels:
  map:{map_id}:
    messages:
      dataset:create:
        payload:
          "$ref": "#/definitions/DatasetCreatePayload"
        replies:
          ok:
            type: string
    notifications: {}
